
---
title: "Latin Square Experiment"
author: "Axel Baudot"
format:
  html:
    code-fold: true
---

# Latin Square Experiment

Latin Square are turned into a COP as we try to maximize the sum of the diagonal.

Different models and branching schemes are compared on the same instances.

```{python}
import plot

instance_numbers = range(1, 11)

models = [
  'dfs-sum_product-max_marginal_regret',
  'dfs-sum_product-max_marginal_strength',
  'dfs-sum_product-max_marginal_regret-oracle',
  'dfs-sum_product-max_marginal_strength-oracle',
  'dfs-max_product-max_marginal_regret-oracle',
  'dfs-max_product-max_marginal_strength-oracle',
]
```

## 500 Holes

Same metrics on every graph, the slowest models are removed to change scale and make the graph more readable.



```{python}
  plot.hole_tables(n=30, holes=500, models=models, instance_numbers=instance_numbers)
  plot.fail_graph(n=30, holes=500, models=models, instance_numbers=instance_numbers)
```

## 600 Holes

```{python}
  plot.hole_tables(n=30, holes=600, models=models, instance_numbers=instance_numbers)
  plot.fail_graph(n=30, holes=600, models=models, instance_numbers=instance_numbers)
```

## 700 Holes

```{python}
  plot.hole_tables(n=30, holes=700, models=models, instance_numbers=instance_numbers)
  plot.fail_graph(n=30, holes=700, models=models, instance_numbers=instance_numbers)
```

# Impact of a constraint z >= 0.5 * max(z)

Truncating the domain of the objective to 50% of its maximum value. Won't make instances unsat or even skip first solutions found (they are usually above this threshold).

Mostly it doubles the slope of the oracle function.

**max_product-max_marginal_regret-oracle** is almost unaffected.

Various effects for the other models : speed up, slow down, no effect... depending on the instance.

Slow down is really surprising for **sum_product-max_marginal_regret** (no-oracle) as it supposedly only restricts the search space.

Graphs : one color for each model, lighter and left is untruncated, darker and right is truncated.

```{python}
  models_truncated = [
    'dfs-sum_product-max_marginal_regret',
    'dfs-sum_product-max_marginal_regret-truncate50',
    'dfs-sum_product-max_marginal_regret-oracle',
    'dfs-sum_product-max_marginal_regret-oracle-truncate50',
    'dfs-max_product-max_marginal_regret-oracle',
    'dfs-max_product-max_marginal_regret-oracle-truncate50',
  ]

  plot.fail_graph(n=30, holes=500, models=models_truncated, instance_numbers=instance_numbers)
  plot.fail_graph(n=30, holes=600, models=models_truncated, instance_numbers=instance_numbers)
  plot.fail_graph(n=30, holes=700, models=models_truncated, instance_numbers=instance_numbers)
```

# Evolution of solution score

```{python}
  models_failure = [
    'dfs-sum_product-max_marginal_regret',
    'dfs-sum_product-max_marginal_regret-oracle',
    'dfs-max_product-max_marginal_regret-oracle',
  ]
  plot.quality_graph(n=30, holes=500, models=models_failure, instance_number=1)
  plot.quality_graph(n=30, holes=500, models=models_failure, instance_number=5)
  plot.quality_graph(n=30, holes=600, models=models_failure, instance_number=1)
  plot.quality_graph(n=30, holes=700, models=models_failure, instance_number=1)
```
